code --install-extension 2211896472.snippets
code --install-extension aaron-bond.better-comments
code --install-extension abusaidm.html-snippets
code --install-extension alexiv.vscode-angular2-files
code --install-extension Angular.ng-template
code --install-extension bengreenier.vscode-node-readme
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension chenxsan.vscode-standardjs
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cmstead.jsrefactor
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension danielpinto8zz6.c-cpp-compile-run
code --install-extension danwahlin.angular2-snippets
code --install-extension dbaeumer.vscode-eslint
code --install-extension dkundel.vscode-npm-source
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.jquerysnippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-pack
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.vscode-mysql
code --install-extension foxundermoon.shell-format
code --install-extension gluons.vscode-atom-javascript-snippet
code --install-extension hars.CppSnippets
code --install-extension HookyQR.beautify
code --install-extension icrawl.discord-vscode
code --install-extension infinity1207.angular2-switcher
code --install-extension jasonnutter.search-node-modules
code --install-extension jmsv.JavaScriptSnippetsStandard
code --install-extension joelday.docthis
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension Mikael.Angular-BeastCode
code --install-extension mikestead.dotenv
code --install-extension miramac.vscode-exec-node
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.js-atom-grammar
code --install-extension ms-vscode.typescript-javascript-grammar
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.debugger-for-edge
code --install-extension mtxr.sqltools
code --install-extension natewallace.angular2-inline
code --install-extension nathanchapman.JavaScriptSnippets
code --install-extension naumovs.color-highlight
code --install-extension nrwl.angular-console
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension rbbit.typescript-hero
code --install-extension sburg.vscode-javascript-booster
code --install-extension Sophisticode.php-formatter
code --install-extension steoates.autoimport
code --install-extension stevencl.addDocComments
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension tht13.html-preview-vscode
code --install-extension truman.autocomplate-shell
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xyz.plsql-language
code --install-extension Zignd.html-css-class-completion
